UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Equipment[@key=''_036CE062'']/Slot/Item[@key=''29'']/Supply/Item[@key=''photocathode'']/Amperage'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_045СЕ110'']/Adress/Item[@key=''29'']/Channel/Item[@key=''1'']/Amperage';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Equipment[@key=''_036CE062'']/Slot/Item[@key=''29'']/Supply/Item[@key=''photocathode'']/Voltage'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_045СЕ110'']/Adress/Item[@key=''29'']/Channel/Item[@key=''1'']/Voltage';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Equipment[@key=''_036CE062'']/Slot/Item[@key=''29'']/Supply/Item[@key=''microchannelplate'']/Amperage'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_045СЕ110'']/Adress/Item[@key=''29'']/Channel/Item[@key=''2'']/Amperage';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Equipment[@key=''_036CE062'']/Slot/Item[@key=''29'']/Supply/Item[@key=''microchannelplate'']/Voltage'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_045СЕ110'']/Adress/Item[@key=''29'']/Channel/Item[@key=''2'']/Voltage';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Equipment[@key=''_036CE062'']/Slot/Item[@key=''29'']/Supply/Item[@key=''anode'']/Amperage'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_045СЕ110'']/Adress/Item[@key=''29'']/Channel/Item[@key=''3'']/Amperage';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Equipment[@key=''_036CE062'']/Slot/Item[@key=''29'']/Supply/Item[@key=''anode'']/Voltage'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_045СЕ110'']/Adress/Item[@key=''29'']/Channel/Item[@key=''3'']/Voltage';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Equipment[@key=''_036CE062'']/Slot/Item[@key=''29'']/Supply/Item[@key=''embedded'']/Amperage'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_045СЕ110'']/Adress/Item[@key=''29'']/Channel/Item[@key=''4'']/Amperage';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Equipment[@key=''_036CE062'']/Slot/Item[@key=''29'']/Supply/Item[@key=''embedded'']/Voltage'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_045СЕ110'']/Adress/Item[@key=''29'']/Channel/Item[@key=''4'']/Voltage';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Equipment[@key=''_036CE062'']/Slot/Item[@key=''29'']/Illuminator/Item[@key=''1'']/Amperage'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_045СЕ100'']/Adress/Item[@key=''36'']/Channel/Item[@key=''10'']/Amperage';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Equipment[@key=''_036CE062'']/Slot/Item[@key=''29'']/Illuminator/Item[@key=''1'']/Voltage'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_045СЕ100'']/Adress/Item[@key=''36'']/Channel/Item[@key=''10'']/Voltage';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Equipment[@key=''_036CE062'']/Slot/Item[@key=''29'']/Illuminator/Item[@key=''2'']/Amperage'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_045СЕ100'']/Adress/Item[@key=''36'']/Channel/Item[@key=''11'']/Amperage';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Equipment[@key=''_036CE062'']/Slot/Item[@key=''29'']/Illuminator/Item[@key=''2'']/Voltage'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_045СЕ100'']/Adress/Item[@key=''36'']/Channel/Item[@key=''11'']/Voltage';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Equipment[@key=''_036CE062'']/Slot/Item[@key=''29'']/Illuminator/Item[@key=''3'']/Amperage'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_045СЕ100'']/Adress/Item[@key=''36'']/Channel/Item[@key=''12'']/Amperage';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Equipment[@key=''_036CE062'']/Slot/Item[@key=''29'']/Illuminator/Item[@key=''3'']/Voltage'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062.Runtime'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_045СЕ100'']/Adress/Item[@key=''36'']/Channel/Item[@key=''12'']/Voltage';
