UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062'']/Equipment[@key=''_036CE062'']/Elegaz/Item[@key='''']/Command/Item[@key=''on'']/Amperage'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_045СЕ87'']/Adress/Item[@key=''40'']/Channel/Item[@key=''1'']/Amperage';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062'']/Equipment[@key=''_036CE062'']/Elegaz/Item[@key='''']/Command/Item[@key=''on'']/Voltage'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_045СЕ87'']/Adress/Item[@key=''40'']/Channel/Item[@key=''1'']/Voltage';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062'']/Equipment[@key=''_036CE062'']/Elegaz/Item[@key='''']/Command/Item[@key=''on'']/Amperage'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_045СЕ87'']/Adress/Item[@key=''40'']/Channel/Item[@key=''B'']/Amperage';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062'']/Equipment[@key=''_036CE062'']/Elegaz/Item[@key='''']/Command/Item[@key=''on'']/Voltage'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_045СЕ87'']/Adress/Item[@key=''40'']/Channel/Item[@key=''B'']/Voltage';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062'']/Equipment[@key=''_036CE062'']/Termodat/Adress/Item[@key=''?'']/Channel/Item[@key=''01'']/Command/Item[@key=''0001'']/Temperature'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_Termodat'']/Adress/Item[@key=''1A'']/Channel/Item[@key=''0170'']/Command/Item[@key=''0001'']/Temperature';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062'']/Equipment[@key=''_036CE062'']/Termodat/Adress/Item[@key=''?'']/Channel/Item[@key=''01'']/Command/Item[@key=''0001'']/Timespan'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_Termodat'']/Adress/Item[@key=''1A'']/Channel/Item[@key=''0170'']/Command/Item[@key=''0001'']/Timespan';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062'']/Equipment[@key=''_036CE062'']/Termodat/Adress/Item[@key=''?'']/Channel/Item[@key=''01'']/Command/Item[@key=''0005'']/Temperature'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_Termodat'']/Adress/Item[@key=''1A'']/Channel/Item[@key=''0170'']/Command/Item[@key=''0005'']/Temperature';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062'']/Equipment[@key=''_036CE062'']/Termodat/Adress/Item[@key=''?'']/Channel/Item[@key=''01'']/Command/Item[@key=''0005'']/Rate'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_Termodat'']/Adress/Item[@key=''1A'']/Channel/Item[@key=''0170'']/Command/Item[@key=''0005'']/Rate';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062'']/Equipment[@key=''_036CE062'']/Termodat/Adress/Item[@key=''?'']/Channel/Item[@key=''01'']/Command/Item[@key=''0006'']/Temperature'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_Termodat'']/Adress/Item[@key=''1A'']/Channel/Item[@key=''0170'']/Command/Item[@key=''0006'']/Temperature';

UPDATE glossary SET configuration = 'Configuration[@key=''_036CE062.ControlWorkstation'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062'']/Equipment[@key=''_036CE062'']/Termodat/Adress/Item[@key=''?'']/Channel/Item[@key=''01'']/Command/Item[@key=''0006'']/Rate'
WHERE communication = 'Configuration[@key=''_036CE062.Communicator'']/Scale/Communication/Item[@key=''database'']/Postgres/Item[@key=''localhost:5432:_036CE062'']/Communication/Item[@key=''serialport'']/Modbus/Item[@key=''COM1'']/Board/Item[@key=''_Termodat'']/Adress/Item[@key=''1A'']/Channel/Item[@key=''0170'']/Command/Item[@key=''0006'']/Rate';
